name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubunto-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0
     
